php:
  image: viljaste/php:5.2
  hostname: php
  ports:
    - "9000:9000"
  environment:
    - SERVER_NAME=localhost
    - DRUPAL_VERSION=6
    - REALPATH_CACHE_SIZE=256k
    - REALPATH_CACHE_TTL=3600
    - POST_MAX_SIZE=512M
    - TIMEZONE=UTC
    - UPLOAD_MAX_FILESIZE=512M
    - SHORT_OPEN_TAG=On
    - MAX_EXECUTION_TIME=300
    - MAX_INPUT_VARS=4096
    - MEMORY_LIMIT=512M
    - DISPLAY_ERRORS=On
    - DISPLAY_STARTUP_ERRORS=On
    - ERROR_REPORTING=E_ALL
    - OPCACHE=On
    - OPCACHE_MEMORY_CONSUMPTION=2048
    - XDEBUG=On
    - XDEBUG_REMOTE_PORT=9000
    - XDEBUG_REMOTE_HOST=127.0.0.1
    - XDEBUG_REMOTE_CONNECT_BACK=On
    - XDEBUG_IDEKEY=PHPSTORM
    - MEMCACHED=On
    - REDIS=On
    - APCU=On
    - APD=On
